---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: true
    exclude_fingerprints:
    - 81f1db8cc66fe7d124f1ecde5904b4e5

  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- test/
- vendor/
